"""add fields to faculty_loads

Revision ID: 11dafebb567e
Revises: abb8c4dda683
Create Date: 2024-03-01 08:17:55.667648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dafebb567e'
down_revision = 'abb8c4dda683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_year', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_loads', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('school_year')
    # ### end Alembic commands ###
