"""create subjects table

Revision ID: 13698eabffd2
Revises: 1741c3f2bdf4
Create Date: 2024-02-27 16:04:04.051477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13698eabffd2'
down_revision = '1741c3f2bdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descriptive_title', sa.String(length=255), nullable=False),
    sa.Column('course_number', sa.String(length=255), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=False),
    sa.Column('laboratory_hours', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_number'),
    sa.UniqueConstraint('descriptive_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    # ### end Alembic commands ###
