"""add room to faculty_loads

Revision ID: 2d421d5af9bc
Revises: 978595c57723
Create Date: 2024-03-07 19:41:18.817762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d421d5af9bc'
down_revision = '978595c57723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_loads', schema=None) as batch_op:
        batch_op.drop_column('room')

    # ### end Alembic commands ###
