"""modify subjects table

Revision ID: 2d995a20be0a
Revises: 14dff2be797c
Create Date: 2024-02-28 10:42:30.250411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d995a20be0a'
down_revision = '14dff2be797c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_year', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('school_year')
    # ### end Alembic commands ###
