"""add fields to students

Revision ID: a106fcf1fc3d
Revises: 2d421d5af9bc
Create Date: 2024-03-08 09:49:51.695642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a106fcf1fc3d'
down_revision = '2d421d5af9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('year_level', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_student_id_students', ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_id_students', type_='unique')
        batch_op.drop_column('year_level')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('gender')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
