"""create faculty_loads table

Revision ID: abb8c4dda683
Revises: 0a87dbd62569
Create Date: 2024-02-29 22:17:57.592806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb8c4dda683'
down_revision = '0a87dbd62569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instructor_id', 'subject_id', name='uq_faculty_load')
    )
    op.create_table('faculty_load_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_load_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_load_id'], ['faculty_loads.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_load_id', 'student_id', name='uq_faculty_load_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_load_student')
    op.drop_table('faculty_loads')
    # ### end Alembic commands ###
