"""add fields_to_faculty_loads

Revision ID: da0af5f9040a
Revises: 11dafebb567e
Create Date: 2024-03-01 09:09:45.520842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0af5f9040a'
down_revision = '11dafebb567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('time_start', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('time_end', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_loads', schema=None) as batch_op:
        batch_op.drop_column('time_end')
        batch_op.drop_column('time_start')
        batch_op.drop_column('day')
    # ### end Alembic commands ###
