"""rename school_year field in subjects

Revision ID: f361f13d77ed
Revises: 2d995a20be0a
Create Date: 2024-02-28 10:49:06.673589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f361f13d77ed'
down_revision = '2d995a20be0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_level', sa.String(length=255), nullable=False))
        batch_op.drop_column('school_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_year', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('year_level')
    # ### end Alembic commands ###
